
try:
    import artifactory_utils
except:
    pass
else:
    dependencies = [
        artifactory_utils.ArtifactSelector(
            project="Toolchain-Release",
            revision="ReleaseMorepork0.59",
            version="^4.6",
            debug=False,
            stable_required=True),
        artifactory_utils.ArtifactSelector(
            project="morepork-build-root",
            revision="HotfixMorepork1.3.1",
            debug=False,
            stable_required=True),
        artifactory_utils.ArtifactSelector(
            project="morepork-mbcoreutils",
            revision="ReleaseMorepork1.3",
            version="^4.0",
            debug=False,
            stable_required=True),
        artifactory_utils.ArtifactSelector(
            project="morepork-json-cpp",
            revision="ReleaseMorepork0.59",
            debug=False,
            stable_required=True),
        artifactory_utils.ArtifactSelector(
            project="morepork-jsonrpc",
            revision="ReleaseMorepork0.59",
            debug=False,
            stable_required=True),
        artifactory_utils.ArtifactSelector(
            project="morepork-libtinything",
            revision="ReleaseMorepork1.4",
            debug=False,
            stable_required=True),
    ]
