#!/bin/sh

# Older version of the sombrero printer use a screen where the capacitive
# touch panel and the RGB panel are aligned. The entire display was upside down
# though and required us to apply a 180 degree rotation to the screen. Newer
# versions of the display have the touch and RGB panels rotated 180 degrees
# from each other. Also, the RGB panel is now upright so we no longer need to
# rotate the display.

# This script creates the file /home/use_new_display.blank

# The pressence of the above file is cheked by both
# morepork_ui_new_display.service and morepork_ui.service. If the file
# exists, morepork_ui_new_display.service will start the UI with the
# --rotate_display_180 option. If the file does not exist, morepork_ui.service
# will start the UI with no rotation option, but will include an environment
# variable that rotates only the capactive touch input.

touch /home/use_new_display.blank

systemctl stop morepork_ui
systemctl restart morepork_ui_new_display
